import sqlite3
print('Tables in ./skillbridge.db:')
conn = sqlite3.connect('./skillbridge.db')
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())
conn.close()

print()
print('Tables in D:/FOAI/Skillbridge/backend/skillbridge.db:')
conn = sqlite3.connect('D:/FOAI/Skillbridge/backend/skillbridge.db')
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())
conn.close()