import { useEffect,useState } from 'react';
import { analyzeSkillGap,listCareerRoles } from '../services/api';
import type { CareerRoleSummary,SkillGapAnalysis,SkillGapMatch } from '../types';
import { Icon } from '../components/Layout';
function CareerPage(){const [roles,setRoles]=useState<CareerRoleSummary[]>([]);const [selected,setSelected]=useState('');const [gap,setGap]=useState<SkillGapAnalysis|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const studentId=typeof window!=='undefined'?localStorage.getItem('skillbridge_student_id'):null;const storedRoleId=typeof window!=='undefined'?localStorage.getItem('skillbridge_selected_role_id'):null;
useEffect(()=>{listCareerRoles().then(r=>{setRoles(r);if(r[0])setSelected(r.find(role=>role.id===storedRoleId)?.id??r[0].id)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load roles'));},[storedRoleId]);
useEffect(()=>{let cancelled=false;setGap(null);if(!selected||!studentId){setLoading(false);return()=>undefined;}setLoading(true);setError('');analyzeSkillGap(studentId,selected).then(data=>{if(!cancelled)setGap(data)}).catch(e=>{if(!cancelled){setGap(null);setError(e instanceof Error?e.message:'Unable to analyze skill gap')}}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[selected,studentId]);
useEffect(()=>{if(!roles.length||typeof window==='undefined')return;if(selected){localStorage.setItem('skillbridge_selected_role_id',selected);window.dispatchEvent(new CustomEvent<string>('skillbridge-role-change',{detail:selected}))}else{localStorage.removeItem('skillbridge_selected_role_id');window.dispatchEvent(new CustomEvent<string>('skillbridge-role-change',{detail:''}))}},[selected,roles.length]);
const role=roles.find(r=>r.id===selected);const all=[...(gap?.matched_strong??[]),...(gap?.matched_weak??[]),...(gap?.matched_missing??[])];return <div className="page-enter"><div className="page-heading"><div><span className="section-kicker">CAREER INTELLIGENCE</span><h2>Find your strongest path</h2><p>Compare your current capabilities against the requirements of a target role.</p></div><div className="target-select"><span>Target role</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div></div>{error&&<div className="notice">{error}</div>}
{role&&<section className="career-hero glass-card"><div><span className="soft-badge">{role.category}</span><h3>{role.name}</h3><p>{role.description}</p><div className="role-meta"><span>{role.required_skill_count} required</span><span>{role.core_skills} core</span><span>{role.critical_skills} critical</span></div></div><div className="career-score"><span>Coverage</span><strong>{loading?'—':`${gap?.skill_coverage_percent??0}%`}</strong><div className="bar"><i style={{width:`${gap?.skill_coverage_percent??0}%`}}/></div></div></section>}
<div className="metric-grid"><Stat label="Strong" value={gap?.summary.strong_count??'—'} tone="green"/><Stat label="Needs work" value={gap?.summary.weak_count??'—'} tone="orange"/><Stat label="Missing" value={gap?.summary.missing_count??'—'} tone="purple"/><Stat label="Core coverage" value={gap?`${gap.core_skill_coverage_percent}%`:'—'} tone="blue"/></div>
<section className="glass-card"><div className="card-head"><div><span className="section-kicker">SKILL GAP</span><h3>Role requirements vs. your profile</h3></div>{gap&&<span className="soft-badge">{gap.total_skills_acquired}/{gap.total_skills_required} covered</span>}</div>{gap?<div className="gap-list">{all.map(m=><GapRow key={`${m.skill_id}-${m.match_status}`} m={m}/>)}</div>:<div className="empty-state"><div className="empty-icon"><Icon name="target"/></div><h3>Select a target career</h3><p>Choose a role above to generate your personalized skill-gap analysis.</p></div>}</section></div>}
function Stat({label,value,tone}:{label:string;value:string|number;tone:string}){return <div className={`metric-card ${tone}`}><div className="metric-icon"><Icon name="target" size={17}/></div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>Role analysis</small></div></div>};function GapRow({m}:{m:SkillGapMatch}){return <div className="gap-row"><div className={`gap-status ${m.match_status}`}>{m.match_status==='strong'?'✓':m.match_status==='weak'?'~':'!'}</div><div className="gap-main"><strong>{m.skill_name}</strong><span>Required: {m.required_proficiency} {m.current_proficiency?`• Current: ${m.current_proficiency}`:''}</span></div><span className="gap-priority">{m.priority}</span></div>};export default CareerPage;
