import { useEffect, useMemo, useState } from 'react';
import { addSelfReportedSkill, getSkills } from '../modules/student-profile/service';
import type { StudentSkillResponse } from '../modules/student-profile/types';
import { Icon } from '../components/Layout';

const rank: Record<string, number> = { beginner: 1, intermediate: 2, advanced: 3 };
function SkillsPage() {
  const [skills, setSkills] = useState<StudentSkillResponse[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [form,setForm]=useState({skill_id:'',proficiency:'beginner' as 'beginner'|'intermediate'|'advanced'});
  const studentId = typeof window !== 'undefined' ? localStorage.getItem('skillbridge_student_id') : null;
  useEffect(()=>{ if(!studentId){setLoading(false);return;} getSkills(studentId).then(setSkills).catch(e=>setError(e instanceof Error?e.message:'Unable to load skills')).finally(()=>setLoading(false)); },[studentId]);
  const counts=useMemo(()=>({advanced:skills.filter(s=>s.proficiency==='advanced').length,intermediate:skills.filter(s=>s.proficiency==='intermediate').length,beginner:skills.filter(s=>s.proficiency==='beginner').length}),[skills]);
  const add=async(e:React.FormEvent)=>{e.preventDefault(); if(!studentId||!form.skill_id.trim())return; setError(null); try{const data=await addSelfReportedSkill(studentId,form);setSkills(p=>[...p,data]);setForm({skill_id:'',proficiency:'beginner'});}catch(err){setError(err instanceof Error?err.message:'Unable to add skill');}};
  return <div className="page-enter"><div className="page-heading"><div><span className="section-kicker">CAPABILITY MAP</span><h2>My Skills</h2><p>Your current capabilities, extracted and assessed by SkillBridge AI.</p></div><div className="heading-stat"><strong>{skills.length}</strong><span>skills tracked</span></div></div>
    {error&&<div className="notice">{error}</div>}
    <div className="metric-grid"><Metric label="Advanced" value={counts.advanced} tone="purple"/><Metric label="Intermediate" value={counts.intermediate} tone="blue"/><Metric label="Beginner" value={counts.beginner} tone="orange"/><Metric label="Profile signal" value={skills.length?'Active':'Empty'} tone="green"/></div>
    <div className="content-two"><section className="glass-card"><div className="card-head"><div><span className="section-kicker">YOUR CAPABILITIES</span><h3>Skill inventory</h3></div></div>{loading?<div className="skeleton-list">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>:skills.length?<div className="skill-grid">{skills.map(s=><SkillCard key={s.id} skill={s}/>)}</div>:<div className="empty-state"><div className="empty-icon"><Icon name="spark"/></div><h3>No skills yet</h3><p>Create your profile or add skills below to build your capability map.</p></div>}</section>
    <section className="glass-card add-skill"><div className="card-head"><div><span className="section-kicker">QUICK UPDATE</span><h3>Add a skill</h3></div></div><form onSubmit={add}><label>Skill name or ID<input value={form.skill_id} onChange={e=>setForm({...form,skill_id:e.target.value})} placeholder="e.g. Python"/></label><label>Proficiency<select value={form.proficiency} onChange={e=>setForm({...form,proficiency:e.target.value as typeof form.proficiency})}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><button type="submit" className="primary-button">Add capability <Icon name="arrow" size={15}/></button></form><div className="hint"><Icon name="spark" size={15}/> Resume-derived skills can also appear here automatically.</div></section></div>
  </div>;
}
function SkillCard({skill}:{skill:StudentSkillResponse}){const pct=(rank[skill.proficiency]??1)/3*100; return <div className="skill-card"><div className="skill-top"><div className="skill-avatar"><Icon name="spark" size={15}/></div><span className={`skill-source ${skill.source==='resume'?'auto':''}`}>{skill.source==='resume'?'AI':'Self'}</span></div><strong>{skill.skill_id}</strong><div className="skill-level"><span>{skill.proficiency}</span><b>{Math.round(pct)}%</b></div><div className="bar"><i style={{width:`${pct}%`}}/></div></div>}
function Metric({label,value,tone}:{label:string;value:string|number;tone:string}){return <div className={`metric-card ${tone}`}><div className="metric-icon"><Icon name="spark" size={17}/></div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>Current profile</small></div></div>}
export default SkillsPage;
